general:
  input_data_path: "data/input"
  output_data_path: "data/output"

census_config:
  EW_1851:
    runtype: "testing"
    use_existing_files: "no"
    census_file: "census_anonymisation_egress/EW1851_anonymised_s.txt"
    census_fields:
      uid: "safehaven_id"
      address: "address_anonymised"
      consistentparid: "ConParID"
      parid: "ParID"
      county: "RegCnty"

    csv_params: # parameters passed to dask read_csv
      sep: "\t"
      encoding: "latin-1"
      blocksize: "25e6"
      quoting: 3
      na_values: "."

    census_standardisation_file: "icem_street_standardisation.json"
    census_output_params:
      partition_on: "RegCnty" # must be in 'census_fields'

  EW_1861:
    runtype: "testing"
    use_existing_files: "no"
    census_file: "census_anonymisation_egress/EW1861_anonymised.txt"
    census_fields:
      uid: "safehaven_id"
      address: "address_anonymised"
      consistentparid: "ConParID"
      parid: "ParID"
      county: "RegCnty"

    csv_params: # parameters passed to dask read_csv
      sep: "\t"
      encoding: "latin-1"
      blocksize: "25e6"
      quoting: 3
      na_values: "."

    census_standardisation_file: "icem_street_standardisation.json"
    census_output_params:
      partition_on: "RegCnty" # must be in 'census_fields'

  EW_1881:
    runtype: "testing"
    use_existing_files: "no"
    census_file: "census_anonymisation_egress/EW1881_anonymised.txt"
    census_fields:
      uid: "safehaven_id"
      address: "address_anonymised"
      consistentparid: "ConParID"
      parid: "ParID"
      county: "RegCnty"

    csv_params: # parameters passed to dask read_csv
      sep: "\t"
      encoding: "latin-1"
      blocksize: "25e6"
      quoting: 3
      na_values: "."

    census_standardisation_file: "icem_street_standardisation.json"
    census_output_params:
      partition_on: "RegCnty" # must be in 'census_fields'

  EW_1891:
    runtype: "testing"
    use_existing_files: "no"
    census_file: "census_anonymisation_egress/EW1891_anonymised.txt"
    census_fields:
      uid: "safehaven_id"
      address: "address_anonymised"
      consistentparid: "ConParID"
      parid: "ParID"
      county: "RegCnty"

    csv_params: # parameters passed to dask read_csv
      sep: "\t"
      encoding: "latin-1"
      blocksize: "25e6"
      quoting: 3
      na_values: "."

    census_standardisation_file: "icem_street_standardisation.json"
    census_output_params:
      partition_on: "RegCnty" # must be in 'census_fields'

  EW_1901:
    runtype: "testing"
    use_existing_files: "no"
    census_file: "census_anonymisation_egress/EW1901_anonymised.txt"
    census_fields:
      uid: "safehaven_id"
      address: "address_anonymised"
      consistentparid: "ConParID"
      parid: "ParID"
      county: "RegCnty"

    csv_params: # parameters passed to dask read_csv
      sep: "\t"
      encoding: "latin-1"
      blocksize: "25e6"
      quoting: 3
      na_values: "."

    census_standardisation_file: "icem_street_standardisation.json"
    census_output_params:
      partition_on: "RegCnty" # must be in 'census_fields'

  EW_1911:
    runtype: "testing"
    use_existing_files: "no"
    census_file: "census_anonymisation_egress/EW1911_anonymised.txt"
    census_fields:
      uid: "safehaven_id"
      address: "address_anonymised"
      consistentparid: "ConParID"
      parid: "ParID"
      county: "RegCnty"

    csv_params: # parameters passed to dask read_csv
      sep: "\t"
      encoding: "latin-1"
      blocksize: "25e6"
      quoting: 3
      na_values: "."

    census_standardisation_file: "icem_street_standardisation.json"
    census_output_params:
      partition_on: "RegCnty" # must be in 'census_fields'

ew_config:
  parish_gis_config:
    filepath: "1851EngWalesParishandPlace/1851EngWalesParishandPlace.shp"
    projection: "EPSG:27700"
    id_field: "ID"

  rsd_gis_config:
    filepath: "ew/rsd_boundary_data/RSD_1851_1911_JR.shp"
    projection: "EPSG:27700"

  rsd_dictionary_config:
    parentdir: "ew/parish_dicts_encoding"
    "1851":
      filepath: "1851_ICeM_DICTIONARY_CODED.txt"
      cen_parid_field: "ParID"
      rsd_id_field: "CEN_1851"
      encoding: "utf-8"

    "1861":
      filepath: "1861_ICeM_DICTIONARY_CODED.txt"
      cen_parid_field: "ParID"
      rsd_id_field: "CEN_1861"
      encoding: "utf-8"

    "1881":
      filepath: "1881_ICeM_DICTIONARY_CODED.txt"
      cen_parid_field: "NEW_ParID"
      rsd_id_field: "CEN_1881"
      encoding: "utf-8"

    "1891":
      filepath: "1891_ICeM_DICTIONARY_CODED.txt"
      cen_parid_field: "ParID"
      rsd_id_field: "CEN_1891"
      encoding: "utf-8"

    "1901":
      filepath: "1901_ICeM_DICTIONARY_CODED.txt"
      cen_parid_field: "ParID"
      rsd_id_field: "CEN_1901"
      encoding: "utf-8"

    "1911":
      filepath: "1911_ICeM_DICTIONARY_CODED.txt"
      cen_parid_field: "ParID"
      rsd_id_field: "CEN_1911"
      encoding: "utf-8"

  parish_icem_lkup_config:
    filepath: "UKDS_GIS_to_icem.xlsx"
    sheet: "link"
    ukds_id_field: "UKDS_ID"
    na_values: "."
    conparid51-91_field: "conparid_51-91"
    conparid01-11_field: "conparid_01-11"

scot_config:
  parish_boundary_gis_pre1891: "scot_parish_boundary/CivilParish_pre1891/CivilParish_pre1891.shp"
  parish_boundary_gis_post1891: "scot_parish_boundary/CivilParish1930/CivilParish1930.shp"
  boundary_lkup_tbl: "scot_parish_boundary/scotboundarylinking.xlsx"
  boundary_lkup_id: "ParID_link"

target_geoms:
  os_open_roads:
    data_path: "data/input/oproad_essh_gb-2/data"
    projection: "EPSG:27700"
    file_type: "shp"
    geom_type: "line"
    geometry_format: ""
    file_name: "RoadLink.shp"
    data_fields:
      uid_field: "nameTOID"
      address_field: "name1"
      geometry_field: "geometry"

    standardisation_file: ""
    query_criteria: ""

  gb1900:
    data_path: "data/input/gb1900_gazetteer_complete_july_2018.csv"
    projection: "EPSG:27700"
    file_type: "csv"
    geom_type: "point"
    geometry_format: "coords"
    encoding: "utf-16"
    file_name: ""
    data_fields:
      uid_field: "pin_id"
      address_field: "final_text"
      long_field: "osgb_east"
      lat_field: "osgb_north"

    standardisation_file: "inputs/street_standardisation.json"
    query_criteria: "final_text.str.len() > 5"
